### ISSUE TITLE
PkgEval: julia binary may be missing

### ISSUE THREAD

**Issue by maleadt** [brenhinkeller/StaticMPI.jl#2]
The tests here run `julia ...`, which is fragile: `julia` might not be on PATH, and the binary may be called `julia-debug`, so it's better to use `Base.julia_cmd()`. This causes a PkgEval failure when running in debug mode.

```
Base.IOError("could not spawn `julia --compile=min scripts/mpihello.jl`: no such file or directory (ENOENT)", -2)
StaticMPI.jl: Test Failed at /home/pkgeval/.julia/packages/StaticMPI/EzNpR/test/runtests.jl:20
  Expression: status isa Base.Process
   Evaluated: -1 isa Base.Process
Stacktrace:
 [1] macro expansion
   @ /opt/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:477 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/StaticMPI/EzNpR/test/runtests.jl:20 [inlined]
 [3] macro expansion
   @ /opt/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:1492 [inlined]
 [4] top-level scope
   @ ~/.julia/packages/StaticMPI/EzNpR/test/runtests.jl:7
```

**Comment by brenhinkeller** [comment]
Ah ok, will `Base.julia_cmd()` also be sure not to propagate the `--check-bounds=yes` flag from the test environment to the specified command?

**Comment by brenhinkeller** [comment]
It looks from the docstring like it will, in which case it may not work here

**Comment by maleadt** [comment]
Then you can peek into the Cmd, or use `joinpath(Sys.BINDIR, Base.julia_exename())`.

**Comment by maleadt** [comment]
It's also recommended to use `--startup-file=no`, to avoid leaking anything into the test env.

**Comment by brenhinkeller** [comment]
That sounds workable
